* Blog Topics
** What year to teach apcsa (ab  - sophomore too young)*
** Blog - teaching best practices not always practical
** Blog - any kid can learn, it's easy but it's too hard for teachers must use scripts
**  Blog missing the stuy crowd
** blog  - I have an easier way to do this is in the eye of the beholder

**  Blog - college - a job or finding a calling
**  Blog - note taking on computers 
** "the right way to teach" and practical limitations - 40 minute period / class size etc
<2017-04-29 Sat 08:49>
** active learning vs lecturing (Wed 11:10 talk)
- sometimes teachers don't have time or facilities for active
  learning or non-lecturing.
** Talk in piazza question analysis
- students who ask good questions get better grades
- spin off post - are tools like piazza better than mailing list and
  should we use things like slack
** collaborative exams
** not a sigcse idea  - see comment from
- http://avc.com/2017/03/feature-friday-learn-mode/#disqus_thread
  #+BEGIN_QUOTE
  This is great stuff. I sure wish they would partner with K-12
  content providers and roll these out into schools. Our kids' school
  system is a total mess with regard to mobile and learning
  tech. Every teacher does their own thing and most parents try to be
  proactive to fill in the gaps.
#+END_QUOTE
and talk about the low friction needed for teacher tech adoption

** Utah HS teacher pipeline - 3 level endorsement:
1. Exploring CS - pd based but w/ year round meetings 
   - 2 years to complete
   - they count this experience as the methods course
2. 3 CS courses
   - edx cs50 online
   - three oracle java courses -  1 meeting online
     - free
   - 2 of three above    
3. more cs courses (5 total)
   - add 2 more 
Not sure what happened to the methods course

so they basically just take the courses they're going to teach

** Teaching CS to CS teachers - Princeton
5 day program to do 5 weeks of the course after APCSA
from 9am to 9pm. 
Not meant to be retained and teach the 5 weeks - more to give an
overview and vocabulary for when they get the real deal 

** Public or private repos - copying and cheating
** code.org, teals, CS Education researcher, teacher
- necessary tension between groups even though all working towards CS
  ED

** Designing a class on the fly (matching my class in with 135 and 136)
** Misc

conference schedule too packed running between events to talk to presenters
practitioners view on teaching vs researchers view of teaching

Belief in teachers vs belief in curriculum

nifty.stanford.edu

** Don't hate me because I'm beautiful -- don't dismiss Stuy because it's Stuy
** Don't be a jerk, don't be a bum
** CS and Ed Reform
- link to valerie straus on dems setting up devos: [[https://www.washingtonpost.com/news/answer-sheet/wp/2017/01/21/democrats-reject-her-but-they-helped-pave-the-road-to-education-nominee-devos/?postshare=9221485044671710&tid=ss_tw-bottom&utm_term=.bb6f35e42f16][link]]
- link to valerie straus on dems setting up devos: [[https://www.washingtonpost.com/news/answer-sheet/wp/2017/01/21/democrats-reject-her-but-they-helped-pave-the-road-to-education-nominee-devos/?postshare=9221485044671710&tid=ss_tw-bottom&utm_term=.bb6f35e42f16][link]]
- tech union organizing
  https://www.theguardian.com/technology/2017/jan/24/silicon-valley-fights-donald-trump-peter-thiel-palantir
- Kirsten Gillibrand said: 
  #+BEGIN_QUOTE
  “John King’s tenure in New York was very adversarial, leaving
  families, students and teachers without a voice on important issues,
  and therefore I cannot support his nomination at this time,” says
  Sen. Gillibrand, who voted against King, in a statement.
  
  #+END_QUOTE
  Only dem to do so king won 49 to 40  with most R's voting no
- https://www.youtube.com/watch?v=6xtZ0fEzi3s&

** stuy CS test prep
 cs test prep [[http://www.kgcomputech.com/class/][link]]
 <2017-01-09 Mon 18:16>
** Praxis exam for 
Pat Youngpradit
 If you know about teacher cert, you know how important this is for
developing the CS teacher pipeline. As an example, instead of taking
15-30 credits to get a CS endorsement, a current teacher can just take
the test and be fully converted into a CS teacher. Right now, many of
our teachers may be teaching CS, but they aren't officially CS
teachers. Consider this an important piece of the national puzzle.
<2016-11-30 Wed 18:34>
** Things kids remember
- blight move
- liz and the recursive sock puppets
- pawel - usaco how I code lesson
- Orian - give more than you can
- others
** development environments
- Cartoon Ria posted dilbert http://dilbert.com/strip/2017-01-02
- online repls for classes vs java projects vs maven vs lein etc
- webpack, grunt, gulp, npm, browserify, babel 
- replit what should i use thread: https://www.reddit.com/r/learnprogramming/comments/5rrztj/what_ide_you_recomend_for_a_beginner/
#+BEGIN_SRC sh
tree /tmp/app2

#+END_SRC
#+BEGIN_VERSE


app2
├── dev
│   └── user.clj
├── project.clj
├── README.md
├── resources
│   └── public
│       ├── css
│       │   └── style.css
│       └── index.html
└── src
└── app2
└── core.cljs


#+END_VERSE

#+BEGIN_SRC clojure
(defproject app2 "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :min-lein-version "2.7.1"

  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [org.clojure/core.async "0.2.391"
                  :exclusions [org.clojure/tools.reader]]
                 [reagent "0.6.0"]]

  :plugins [[lein-figwheel "0.5.8"]
            [lein-cljsbuild "1.1.4" :exclusions [[org.clojure/clojure]]]]

  :source-paths ["src"]

  :clean-targets ^{:protect false} ["resources/public/js/compiled" "target"]

  :cljsbuild {:builds
              [{:id "dev"
                :source-paths ["src"]

                ;; the presence of a :figwheel configuration here
                ;; will cause figwheel to inject the figwheel client
                ;; into your build
                :figwheel {:on-jsload "app2.core/on-js-reload"
                           ;; :open-urls will pop open your application
                           ;; in the default browser once Figwheel has
                           ;; started and complied your application.
                           ;; Comment this out once it no longer serves you.
                           :open-urls ["http://localhost:3449/index.html"]}

                :compiler {:main app2.core
                           :asset-path "js/compiled/out"
                           :output-to "resources/public/js/compiled/app2.js"
                           :output-dir "resources/public/js/compiled/out"
                           :source-map-timestamp true
                           ;; To console.log CLJS data-structures make sure you enable devtools in Chrome
                           ;; https://github.com/binaryage/cljs-devtools
                           :preloads [devtools.preload]}}
               ;; This next build is an compressed minified build for
               ;; production. You can build this with:
               ;; lein cljsbuild once min
               {:id "min"
                :source-paths ["src"]
                :compiler {:output-to "resources/public/js/compiled/app2.js"
                           :main app2.core
                           :optimizations :advanced
                           :pretty-print false}}]}

  :figwheel {;; :http-server-root "public" ;; default and assumes "resources"
             ;; :server-port 3449 ;; default
             ;; :server-ip "127.0.0.1"

             :css-dirs ["resources/public/css"] ;; watch and update CSS

             ;; Start an nREPL server into the running figwheel process
             ;; :nrepl-port 7888

             ;; Server Ring Handler (optional)
             ;; if you want to embed a ring handler into the figwheel http-kit
             ;; server, this is for simple ring servers, if this

             ;; doesn't work for you just run your own server :) (see lein-ring)

             ;; :ring-handler hello_world.server/handler

             ;; To be able to open files in your editor from the heads up display
             ;; you will need to put a script on your path.
             ;; that script will have to take a file path and a line number
             ;; ie. in  ~/bin/myfile-opener
             ;; #! /bin/sh
             ;; emacsclient -n +$2 $1
             ;;
             ;; :open-file-command "myfile-opener"

             ;; if you are using emacsclient you can just use
             ;; :open-file-command "emacsclient"

             ;; if you want to disable the REPL
             ;; :repl false

             ;; to configure a different figwheel logfile path
             ;; :server-logfile "tmp/logs/figwheel-logfile.log"
             }


  ;; setting up nREPL for Figwheel and ClojureScript dev
  ;; Please see:
  ;; https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl


  :profiles {:dev {:dependencies [[binaryage/devtools "0.8.2"]
                                  [figwheel-sidecar "0.5.8"]
                                  [com.cemerick/piggieback "0.2.1"]]
                   ;; need to add dev source path here to get user.clj loaded
                   :source-paths ["src" "dev"]
                   ;; for CIDER
                   ;; :plugins [[cider/cider-nrepl "0.12.0"]]
                   :repl-options {; for nREPL dev you really need to limit output
                                  :init (set! *print-length* 50)
                                  :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}}

)


#+END_SRC
** The death of drafting
** Practitioners vs research
Gart: Often it says that things like discovery learning are the best way to learn math when my experience is that it isn't so I don't take that research too seriously.
- Mark's blog https://computinged.wordpress.com/2016/05/23/what-is-the-community-of-practice-for-cs4all-teachers-suggestion-its-not-teachers/

http://crpit.com/confpapers/CRPITV114Lister.pdf


170 students
http://ims.mii.lt/ims/konferenciju_medziaga/SIGCSE'10/docs/p431.pdf
survey 
had tutors do things a little differently

http://files.eric.ed.gov/fulltext/EJ856931.pdf
Participants
One hundred twenty-six girls were voluntary participants in an after-school
and summer program called Girls Creating Games (GCG). They all live in a
small urban community in Central California and range in age from 10 to 14
years (M=11.75, SD=1.0). The girls’ self-reported ethnicity was mostly white
(58%) and Hispanic/Latina (31%); 35% of all girls reported that they speak
a language other than English at home at least some of the time. We collected
data for this part of our work from 10 pairs of girls. We ran our program six
times from spring 2003 to fall 2004. All pairs in the last cohort were audiotaped
if both partners were present on the day we taped. The mean age for this
subgroup is 11.45 (SD=0.61). These girls’ self-reported ethnicity was mostly
white (62%) and Hispanic/Latina (29%); 43% of these girls reported they
speak a language other than English at home at least some of the time. All of
these girls reported they have a computer at home they can use. 






http://ims.mii.lt/ims/konferenciju_medziaga/ICER'10/docs/p69.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.11.8151&rep=rep1&type=pdf
https://docs.google.com/viewer?url=http%3A%2F%2Fhome.cc.gatech.edu%2Fallison%2Fuploads%2F3%2Fguzdial2006.pdf
http://home.cc.gatech.edu/allison/uploads/tew2005b.pdf

** How early to take AP classes - 10th grade too young
- specializing too early
- classes too early - physics first
** Real teachers using moocs and the like (abdicating teaching responsibility)
** What community colleges can do to replace code schools
** digitqpals lesson -- teaching how to approach a problem
** companies pushing training down onto the colleges
** Teacher Movies http://www.npr.org/sections/ed/2014/12/05/368436884/what-the-movies-taught-us-about-teaching
** gateway or gatekeeper  - intentionally leaky pipeline
** Making Tests
good tests finished on time, not make kids cry, time to review not a race
** Cheating - tests and homework
** Rating schools
Fred's graduation speech
** Should we get rid of Stuy (article, test, etc)

** catwo
** Sentence Generator in scheme
:PROPERTIES:
:ID:       d1a94578-88cd-4402-a012-c8f11e1af637
:END:
** Slack
:PROPERTIES:
:ID:       88b3f6c0-9d30-4379-aa00-f1947d0510f7
:END:
** CS Ed people - fracturing programs
:PROPERTIES:
:ID:       c628d48a-47c5-4286-a9bc-62924b6b4d4c
:END:
** tests vs projects - learning for grades vs learning to lean
:PROPERTIES:
:ID:       db5ef82e-95d1-4a3a-97ad-ec78271ca2da
:END:
**** Will that be on the test
:PROPERTIES:
:ID:       cd2ca078-5d86-4e93-b01a-8ee7b6874a7e
:END:
** Scripted curriculum killing creativity (ps 158 tour)
:PROPERTIES:
:ID:       35b7c348-290f-4786-a08a-5be4e3f5ed48
:END:
** Eva S's email
:PROPERTIES:
:ID:       69893f92-8868-4225-830d-c34d6311f082
:END: 
** GWC taking all the girls
:PROPERTIES:
:ID:       f39012c5-fe77-42ce-9ac9-773a7a9037d8
:END:

** Stupid questions
:PROPERTIES:
:ID:       3c914c37-39e9-4b2c-a747-5283fbe74997
:END:
Zabari - how do I regex in find 
real question was doing a search box
Zane -- how do you store a list in sql
he really Wanted - users have tags how do we store them 
how do I use threads?
** Stuyvesant's Brand
:PROPERTIES:
:ID:       b60f9954-7593-46f5-88e7-b5a63877ec0d
:END:
** building a CS program
** Teaching as jazz, comedy, hip hop
** jim vs Gary - Force of personality
:PROPERTIES:
:ID:       e8837240-d301-4d38-8cf4-03fa9d5818fb
:END:
** Bowling ball problem lesson
:PROPERTIES:
:ID:       d2a822cf-8683-433a-910e-78eb7bdfa4d5
:END:
** Intro to recursion
:PROPERTIES:
:ID:       15fa7238-c855-4ec4-bf35-62341f9950d5
:END:
** Bessie travels as CA
*qUU* Wikis as web sites
** Edge detection as CA
**  2d Array topics - image processing
** Doing it right -- Jules using a faster data structure
** Alex Kasinov and USACO
** companies used to train now want colleges to do it - 

