o* Blog Topics
** Blog - teaching best practices not always practical
** Blog - any kid can learn, it's easy but it's too hard for teachers must use scripts
** blog  - I have an easier way to do this is in the eye of the beholder
** "the right way to teach" and practical limitations - 40 minute period / class size etc
<2017-04-29 Sat 08:49>
** Talk in piazza question analysis
- students who ask good questions get better grades
- spin off post - are tools like piazza better than mailing list and
  should we use things like slack
** Don't be a jerk, don't be a bum
** Things kids remember
- blight move
- liz and the recursive sock puppets
- pawel - usaco how I code lesson
- Orian - give more than you can
- others
** Practitioners vs research
Garth: Often it says that things like discovery learning are the best way to learn math when my experience is that it isn't so I don't take that research too seriously.
- Mark's blog https://computinged.wordpress.com/2016/05/23/what-is-the-community-of-practice-for-cs4all-teachers-suggestion-its-not-teachers/

http://crpit.com/confpapers/CRPITV114Lister.pdf


170 students
http://ims.mii.lt/ims/konferenciju_medziaga/SIGCSE'10/docs/p431.pdf
survey 
had tutors do things a little differently

http://files.eric.ed.gov/fulltext/EJ856931.pdf
Participants
One hundred twenty-six girls were voluntary participants in an after-school
and summer program called Girls Creating Games (GCG). They all live in a
small urban community in Central California and range in age from 10 to 14
years (M=11.75, SD=1.0). The girls’ self-reported ethnicity was mostly white
(58%) and Hispanic/Latina (31%); 35% of all girls reported that they speak
a language other than English at home at least some of the time. We collected
data for this part of our work from 10 pairs of girls. We ran our program six
times from spring 2003 to fall 2004. All pairs in the last cohort were audiotaped
if both partners were present on the day we taped. The mean age for this
subgroup is 11.45 (SD=0.61). These girls’ self-reported ethnicity was mostly
white (62%) and Hispanic/Latina (29%); 43% of these girls reported they
speak a language other than English at home at least some of the time. All of
these girls reported they have a computer at home they can use. 






http://ims.mii.lt/ims/konferenciju_medziaga/ICER'10/docs/p69.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.11.8151&rep=rep1&type=pdf
https://docs.google.com/viewer?url=http%3A%2F%2Fhome.cc.gatech.edu%2Fallison%2Fuploads%2F3%2Fguzdial2006.pdf
http://home.cc.gatech.edu/allison/uploads/tew2005b.pdf

** Real teachers using moocs and the like (abdicating teaching responsibility)
** What community colleges can do to replace code schools
** digitqpals lesson -- teaching how to approach a problem
** Teacher Movies http://www.npr.org/sections/ed/2014/12/05/368436884/what-the-movies-taught-us-about-teaching
** catwo
** Sentence Generator in scheme
** Slack
** Stupid questions
:PROPERTIES:
:ID:       3c914c37-39e9-4b2c-a747-5283fbe74997
:END:
Zabari - how do I regex in find 
real question was doing a search box
Zane -- how do you store a list in sql
he really Wanted - users have tags how do we store them 
how do I use threads?
** Bessie travels as CA
** Alex Kasinov and USACO
** companies used to train now want colleges to do it - 

