#+BEGIN_COMMENT
.. title: Using Emacs - 12 - Flycheck, Jedi, Python
.. slug: using-emacs-12-python
.. date: 2016-07-27
.. tags: emacs, tools
.. category:
.. link: 
.. description: 
.. type: text
#+END_COMMENT

*  


This week, we're going to look at my setup for Python programming. 

I'm an educator, not a professional developer so I'm not working in
huge code bases with dozens or more files at a time. I do periodically
work in medium size code bases and will talk about cross file
navigation and project management later on. There are also more
powerful emacs Python packages. One being [[https://github.com/jorgenschaefer/elpy][elpy]]. Elpy looks pretty cool
but for me, it's overkill.

Today's about the basics.

The first tool I show is [[http://www.flycheck.org/en/latest/][flycheck]]. It does code checking on the fly
and supports [[http://www.flycheck.org/en/latest/languages.html#flycheck-languages][tons of languages]]. You might have to install some
external checkers though. For instance, I installed **pylint** for
python syntax checking with:

#+BEGIN_SRC bash
sudo pip install pylint
#+END_SRC

Cofiguring flycheck is as easy as:

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :init
  (global-flycheck-mode t))
#+END_SRC


The video all shows how I like to run Python from within emacs.

The other tool I use is [[https://github.com/tkf/emacs-jedi][Jedi]]. It provides more extensive completion
for Python.

Here's the setup:

#+BEGIN_SRC emacs-lisp
(use-package jedi
  :ensure t
  :init
  (add-hook 'python-mode-hook 'jedi:setup)
  (add-hook 'python-mode-hook 'jedi:ac-setup))
#+END_SRC

The last hook sets up the autocomplete. 

For jedi to work, you'll need to install the jedi server which is done
in emacs by running **M-x jedi:install-server**. For that to work,
though, you'll need to have [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][Python Virtualenv]] istalled. I did that
with:

**EDIT:** I just got a report that you might need to also install epc (**sudo pip install epc**).


#+BEGIN_SRC bash
sudo pip install virtualenv
#+END_SRC

Here's the video:

#+BEGIN_EXPORT HTML
<iframe width="420" height="315" src="https://www.youtube.com/embed/wbj_Wjm1Tuw" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT


Relevant links:
- Flycheck:
  - [[http://flycheck.org][Flycheck home page]]
  - [[https://www.pylint.org/][Pylint]]
  - [[http://flake8.pycqa.org/en/latest/][Flake8]]
- Jedi:
  - [[https://github.com/davidhalter/jedi][Jedi]]
  - [[https://virtualenv.pypa.io/en/stable/][Virtualenv]]
- Video series overview page:
  - http://cestlaz.github.io/stories/emacs
- Code:
  - [[https://github.com/zamansky/using-emacs/tree/master][https://github.com/zamansky/using-emacs/tree/master]]


