#+BEGIN_COMMENT
.. title: BS? - BA - addendum
.. slug: ba-bs2
.. date: 2017-01-02 10:46:51 UTC-05:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 
Over on Facebook, a friend commented on my last post. He commented on
the rigor of BA vs BS degrees. The comment mentioned Physics and Math
degrees but I thought Id follow up a bit on CS degrees.

I took a quick look at three computer science programs - Cornell,
UMich, and Queens College. Cornell because my daughter is there,
UMich, my son, and Queens College because it's a CUNY college that
offers both a BS and a BA in computer science.

** Cornell

Here's a link to Cornell's [[https://www.cs.cornell.edu/undergrad/csmajor][CS Major page]]. Same requirements for a BA
through their School of Arts and Sciences as for their BS in the
School of Engineering. The differences are limited to the fundamental
school differences. 

** University of Michigan

Info on their program can be found [[http://www.eecs.umich.edu/eecs/undergraduate/cs_lsa_vs_engr.html][here]]. They note:

- Identical Core Computer Science requirements
- Similar Senior Design experiences
- Identical Upper Level Elective requirement
- Slight difference in Flexible Technical Elective hours and list

Again, the difference is fundamentally in the base school
requirements.

** Queens College

[[http://www.cs.qc.edu/index-1.html][This page]] has links to degree requirements. THe page states that "The
B.S. augments the B.A. with more computer science, mathematics, and
experimental laboratory courses" but when you look at the actual [[http://www.cs.qc.edu/undergrad/BS.pdf][BS]]
and [[http://www.cs.qc.edu/undergrad/BA.pdf][BA]] requirements, they're the same. 

** 
In all cases, the differences are
the fundamental difference between the extra liberal arts and
distribution requirements in an Arts and Sciences school and the extra
science and math courses required of an engineering school.

Which is better? It all depends. For me, personally, the liberal arts
education is very important. For others, it will be the deep dive into
science. Maybe more phyics will better enable a CS major to solve some
technical problem but then again, maybe a culteral anthropology course
will help a CS major see the world and people differently and also
color her work.

To my original point - the important thing is that we do a better job
informing guidance counselors, teachers, and high school students as
to the possibilities so that they can make informed decisions.









