#+BEGIN_COMMENT
.. title: Using Emacs - Intro to Org Mode
.. slug: using-emacs-2-org
.. date: 2016-05-23 13:29:36 UTC-04:00
.. tags: emacs, tools
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 

#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/x5KiYDd9s8k?list=PL9KxKa8NpFxIcNQa9js7dQQIHc81b0-Xg" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT

This video is a brief introduction to org-mode, a mode I use for all
sorts of things.

We'll dive into org-mode later in the series. Right now I just want
you to see the basics since we'll be using org-mode for any notes that
are written up during this series. 

Actually, all my blog posts are written in org-mode.

Here are the important lines to add to your Emacs *init.el* file  to
get the nice looking bullets when in org-mode:

#+BEGIN_SRC emacs-lisp :tangle no
(use-package org-bullets
  :ensure t
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC


About a month ago, Emacs user Harry Schwartz gave a nice overview talk
on org-mode. If you want to get a better idea as to all the things you
can do with it, check it out: https://www.youtube.com/watch?v=SzA2YODtgK4

Next time, we'll look at a little Elisp. After that, we'll dive in to
using Emacs effectively and efficiently. 

Relevant links:
- Video series overview page:
  - http://cestlaz.github.io/stories/emacs
- Code for this video:
  - [[https://github.com/zamansky/using-emacs/tree/lesson-2-org][https://github.com/zamansky/using-emacs/tree/lesson-2-org]]
- Complete code built up over all videos:
  - [[https://github.com/zamansky/using-emacs/tree/master][https://github.com/zamansky/using-emacs/tree/master]]
- Packages
  - [[https://github.com/sabof/org-bullets][org-bullets]]


