#+TITLE: college-board Stuff`
#+BEGIN_COMMENT
.. title: Remember, school is all about profit, wait no, I mean testing, no, I mean...
.. slug: college-board
.. date: 2016-05-06 07:03:36 UTC-04:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT


It's important to remember, the college board is about making money
for the college board. It's not about supporting teachers and it's
certainly  not about educating kids.


Kids took the AP Computer Science A exam last week and the College
Board just released the free response questions. There seems to me
more chatter about them in social media than in past years.

I'm just left wondering how AP became the be all and end all.

From where I stand, the College Board, who runs AP, SAT, and PSAT
exams is all about making money for the College Board - they're a
non-profit in name only.

It's all about market share and dominance.

Looking at APCS A, it's not a great exam or course. At Stuy, I taught
a super-set of the old AB and pretty much ignored the parts I didn't
like (that is, the case study) but many schools can't do that. In my
case, most of the schools my kids went to didn't award credit, even
for a 5. They did sometimes award placement but I've had just as many,
if not more kids gain placement just by showing their work to the CS
department at their chosen school.

Now they're rolling out APCS Principles. I do get the fact that many
schools don't have people to roll their own courses, but I'm not
overly impressed by much of what's come out. I think what we've
developed is stronger and time proven.

Regardless, and moving beyond just CS, the College Board has somehow
bamboozled the public to think AP = Good. Colleges are awarding less
and less credit but everyone's telling the kids to take more and more
AP classes. What's worse, somehow US News and World Report magically
became an authority on school ratings and now the more AP classes your
kids take the better.

I know of at least one school with a highly lauded principal boast
about all his kids came in behind in math and by their senior year
passed honors calculus. Looking at the data unfortunately showed that
while all his seniors took the class, all failed, scoring below
a 3. It made the school look great but I'd argue that it was child
abuse.

The principal of course parlayed that gig to an even higher profile
one.

Now, you could just file the stupid paperwork so that you can run
classes labeled as AP and have kids take the classes but not the exam
but the College Board's working on that - there are rumblings in NY
on using [[http://www.chalkbeat.org/posts/ny/2016/04/13/new-york-considering-using-scores-on-ap-exams-and-sat-subject-tests-in-teacher-evaluations/#.VyyRlN9vGAk][student AP scores in teacher ratings]]. Using student test
results for teacher ratings is already a bad idea - using AP is even
worse.

Of course, to really get the cash cow going, AP is entering deals with
agencies and municipalities for large scale testing -- in NY students will have to take the
SAT and [[http://nymag.com/daily/intelligencer/2015/10/nyc-will-give-free-sat-testing-to-hs-juniors.html][take it for free]]. Then there's code.org's deal free PD for
school's that have their kids take [[http://cestlaz.github.io/posts/2015-05-19-code-org-college-board.html/][yet another meaningless exam]], the
new PSAT/8-9.

Of course, none of this is free - it's our taxpayer money hard at work
being shuttled right into the college board.

What are we getting? Tests that they create and control and are
EXTREMELY secretive about that don't tell us anyhting that we don't
already know about our kids. Oh, and teachers lose instructional time
and have to [[http://cestlaz.github.io/posts/2015-10-13-psat.html/#.VyzHNN9vGAk][proctor]] these exams instead of teaching.

Great deal if you can get it.

Now, what's the value of this -- more meaningless tests for the
kids. I don't know if there's a record of this anywhere but in the
pre-internet day, I remember watching a news report where a College
Board representative stated that the SAT was a valid predictor of one
thing - how students would do on future SAT exams.

So, were left with more money flowing to an outside company with
students taking more meaningless tests.

I wish more schools showed the backbone that Fieldston, an elite
private school in NY had when it [[http://www.nytimes.com/2002/02/01/nyregion/high-school-drops-its-ap-courses-and-colleges-don-t-seem-to-mind.html][dropped A.P. courses]] over 10 years
ago. They still seem to be well regarded as a school and their kids do
just fine in terms of college acceptance.


 
