#+BEGIN_COMMENT
.. title: Changing Admissions to the NYC Specialized High Schools
.. slug: shsat
.. date: 2018-06-03 07:01:31 UTC-04:00
.. tags: education, policy, gifted ed
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 
Yesterday, Bill de Blasio, the current Mayor of New York City outlined
how he would "fix" our specialized schools. The schools he was
referring to were the "big three" of Stuyvesant, Bronx Science, and
Brooklyn Tech and then five additional schools - The High School  for
Math Science and Engineering at CCNY, The High School for American
Studies at Lehman, Brooklyn Latin, The Queens Arts and Science High
School at
York College, and Staten Island Tech.

All use a single SAT style test, the SHSAT, for admission. The Big Three are
locked into that system unless there are changes made by the state
legislature. The Mayor can make changes to the admissions criteria of
the other five on his own.

The problem, as stated by Chalkbeat writers Alex Zimmerman and  Monica
Disare is that: 

#+BEGIN_QUOTE
The city’s specialized high schools — considered some of the crown
jewels of New York City’s education system — accept students based on
a single test score. Over the last decade, they have come under fire
for offering admissions to few students of color: While two-thirds of
city students are black or Hispanic, only about 10 percent of
admissions offers to those schools go to black or Hispanic students.
#+END_QUOTE

I normally don't write about things like this but given my history at
and with Stuyvesant I thought I should.

Before getting started, my biases - I believe in public schools, not
charters, I also believe that a system should have gifted programs and
magnet schools and also a mix of large comprehensive schools and
smaller niche ones. Additionally, while I do believe in gifted
programs I'm not sure at what point it makes sense to start offering
them. When we were looking at elementary schools for our own kids we
opted for a neighborhood public school rather than applying to the
district gifted program as we felt it offered a better overall
education. On the other hand, had our kids not made Stuyvesant, I'm
not sure what we would have done. Part of that was due to the fact
that the Bloomberg administration destroyed just about all the large
comprehensive schools so, other than that large test schools and
LaGuardia, good luck finding a school that was strong in the
humanities, sciences and offered a robust music program. 

* The overall picture

For reference, here are [[http://www.theschoolboards.com/showthread.php/4324-Specialized-High-School-SHSAT-Cutoff-Scores-for-2018][unofficial cutoff scores]] for the specialized
schools from 2018 along with the NY State data on free and reduced
lunch for 2017. Note that there's overlap between the schools. I
separated out SI Tech since geography probably affects it's numbers
more than the other schools and I separated the big three from the
remaining four because I think the three are all substantially larger. The
free and reduced lunch percent is important because I believe an
entire school qualifies for Title I funding if the number's
over 40 so while these schools are not populated entirely by low
income students, all but HSAS has a substantial number and there's a
chance, some say a good one that at best BdB's plans will merely
shuffle which low income kids get in rather than actually solving the
root problem.

#+ATTR_HTML: :border-spacing 10px :frame border
|----------------+-----------------------+------------+---------------------------|
| School         | Lowest Score admitted | High Score | Pct free or reduced lunch |
|----------------+-----------------------+------------+---------------------------|
| Stuyvesant     |                   559 |        698 |                        46 |
| Bronx Science  |                   518 |        637 |                        45 |
| Brooklyn Tech  |                   493 |        668 |                        62 |
|----------------+-----------------------+------------+---------------------------|
| HSMSE          |                   516 |        616 |                        46 |
| HSAS           |                   516 |        633 |                        25 |
| Brooklyn Latin |                   482 |        555 |                        61 |
| Queens Sci     |                   538 |        542 |                        64 |
|----------------+-----------------------+------------+---------------------------|
| SI Tech        |                   519 |        660 |                        40 |
|----------------+-----------------------+------------+---------------------------|



* The plan
** Part 1 - test prep

There's idea here is that test prep is rampant for SHSAT and that the
test can be gamed. This may or may not be true but if it is then it's
safe to assume that a lot of low income kids are doing test
prep either by prioritizing test prep programs in family budgets,
working off of an SHSAT test prep book or by attending a middle school
that has some form of prep. 

There has long been a program on the books called "The Discovery
Program" which has a free city run test prep component and also a
summer component. The summer component is for low income students who
score within "a few points" of the school in question's cutoff
score. At the end of the summer, I believe the students retest and in
general make the school in question.

*This program is a good thing and should be reinstated* but I don't
know if it will result in the changes that BdB is looking for. More
likely Stuy will get its discovery kids from Science and Science from
Tech. As there are already many low income students at all of the
schools there's no indication that this would increase the number of
under represented groups which is BdB's goal. 

It's also worth noting that there's a sizable chunk of Brooklyn Tech
students that don't perform particularly well on regents exams.
Everyone knows I'm not a fan of standardized tests and I don't
believe that students that score a "few points" lower on the SHSAT are
any less qualified to be in a specialized school but at the lowest
performing end of these schools, one has to ask how specialized is it
really?

** Part 2 - use state test scores instead of the SHSAT

This *could be* a *very* good thing with one major caveat. 

Twenty one middle schools produce over half the students that
ultimately are accepted to the specialized schools. For the rest,
there are a few reasons

- Many students don't take the SHSAT.
- There have been stories of schools steering kids away from the
  specialized schools.
- There's no culture in those schools of striving for specialized
  school acceptance or attendance. 
- The academic programs at those schools don't prepare students for
  the SHSAT exam for reasons that we're not going to delve into here.

All students already take the NY State middle school Math and English
exams. Yes, it would further raise the stakes for those exams but it
would ensure that the specialized schools are on the map for everyone, 

The big question here is "do the current state exams cover enough
material in enough depth to select and differentiate for gifted
programs." I don't know the answer to this question. If they don't
then using state test scores will be a disaster. If they do, then they
could be a suitable alternative.

** Part 3 - admissions from every middle school

This is the third part of BdB's proposal - guarantee admissions to the
top 10% of students at every middle school.

This could be a real disaster either for the students or for the
schools. There's no question that students coming out of different
middle schools are at different levels of preparedness for the
specialized schools. Arguably the most obvious difference is that some
middle schools offer algebra and others don't. 

For better or worse, the specialized school's curricula, classes, and
overall programs have evolved hand in hand with the exam. If you all
of a sudden end up placing a large number of students with a
different and arguable weaker academic profile into these schools one
of two things will happen. Either the students will struggle immensely
or the school will have to lower its standards. There's no two ways
about it.

If you set standards for academic preparedness for the specialized
schools either by making a hard cutoff on an exam score be it state or
SHSAT and then spread those acceptances across all the schools maybe
it could work. If not, you're setting up students with high grades at
schools with weak programs up for failure.

Another problem is what to do with non-public school students -
private schools, charters which take public money but act as private
schools, parochial, and home school students. Where do they fall in to
this equation?


* Is one measure bad?

So there you have my thoughts on BdB's specific proposals but I also
want to address his contention that a single measure is bad and makes
the comparison to colleges where they by and large use multiple
measures. This is a ridiculous comparison. Yes, colleges look at
multiple measures but after watching decades of Stuy students go off
to college, it's clear to me that the process is by no means fair or
consistent. Elite schools can easily game their acceptances and
they still can have 100% of their applicants with off the charts SAT
scores. 

A single test might not be ideal but it can only be gamed by test prep
and test prep can be as cheap as buying a test prep book.

As to other measures that come up from time to time - interviews,
portfolios, essays - who does that help? The low income kid or the
well to do one?

If you're going to add another measure for admission it has to be
something that can't be gamed or politically influenced,

* Alternatives

Should the city address the fact that there are groups that are under
represented at the specialized schools? Certainly, or rather, the city
should address deficiencies in opportunities that are like the causes
of this under representation.

Should the city be doing things differently? Also yes. Here are some
thoughts on what the city can and should be doing.


** Do the experiments in the non-big three.

There are five specialized schools that aren't covered by state
legislation. Why not run your experiments there. You've got  the big
three as a control group and what's more if you look at the
"acceptance score windows" in the table above, you'll see that there's
enough overlap that you can probably get some real data out of these
experiments.

Why not change the admissions criteria for one or two of them and see
how it goes before jumping in whole hog. Figure out if anything works first.

** Check existing data 

We've got SHSAT results and State Test score results along with
student grades for years. Why not study correlations between
them. Rather than making a specious claim about middle school grades
in NYC Public Schools vs state tests vs the SHSAT, run the
numbers. Take a look at student high school performance based on these
predictions. This shouldn't be guess work and city should have the
data to do better.

** Fix the middle schools

This one is more pie in the sky because no politician really wants to
take this one but you've got to look at what's going on in the middle
schools and why. 

I tweeted this the other day:

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">would love to see this experiment - take the entire staff / faculty / admin of one of the 20 or so middle schools that are the primary feeders to the spec schls and swap them with another middle school and see what happens.</p>&mdash; Mike Zamansky (@zamansky) <a href="https://twitter.com/zamansky/status/1003074760786501632?ref_src=twsrc%5Etfw">June 3, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+END_EXPORT

The truth is that if you did this, the high performing school would
probably continue to be high performing and the low performing one
would still struggle. There's only so much a teacher can do. A school
with a disadvantaged population needs the resources to succeed - lower
class sizes for a start. Add wraparound services, extensive after
school and weekend opportunities - make the schools a part of the
community and maybe we can get somewhere.

Another question relating to our schools in general is to look at
attrition rates to private schools - how many students in our under
represented groups are being siphoned off to private schools on
scholarship. I don't have any data for this. It could be an
insignificant amount or it could go a long way in explaining the
downturn in the numbers over the decades. 
 
* So where are we

There are a lot of changes I'd love to see in our public schools and I
do believe BdB's heart is in the right place. I'm concerned that some
of the solutions that he and other politicians come up with will hurt
the current low income students at the specialized schools and
unintentionally advantage the well to do while not helping those that
at least BdB may honestly want to help.

He should enact Discovery and research the State Tests but proceed
with caution. The test schools have always been and continue to be a
gateway for poor and immigrant students and any changes that are
proposed should be weighed carefully and *tested* before taking steps
that could real harm when good is intended.

