#+BEGIN_COMMENT
.. title: Do the students finish the tests or does the test finish the students
.. slug: tests-finish-students
.. date: 2018-04-25 15:53:06 UTC-04:00
.. tags: education, assessments
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 
I tweeted this the other day:

#+BEGIN_EXPORT html
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Why don&#39;t so many  teachers and professors understand that the test or assignment you can do in 15 minutes will take your beginning students at least an hour and probably a lot more to complete.</p>&mdash; Mike Zamansky (@zamansky) <a href="https://twitter.com/zamansky/status/986609723557404673?ref_src=twsrc%5Etfw">April 18, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

#+END_EXPORT

What led to the tweet was a discussion I was having with some students
about not having enough time on tests which led to a discussion of
having to drop everything to spend every waking hour on a project.


** Let's talk about tests.

I'm not saying that tests are the best forms of assessment - most of
the time I'd much rather have students work on projects. There are,
however, times when tests make sense or are otherwise appropriate.

In any event, writing a test is hard. Rather, writing good test is
hard. It's certianly easy enough to put a bunch of multiple choice or
short answer questions on paper and it's easy enough to give a hard
equation to solve or some code to write but creating a good test is a
task and half. You first have to figure out what you're trying to
assess - memory, thought process, synthesizing concepts? Then you want
to construct questions that give you insights into your students
knowledge and thought process.

Some things that I consider when putting together a test:

- Does it ramp up in difficulty - that is, are there some "gimme
  questions" and some challenges.
- Are questions all or nothing - if a kid doesn't see things my way
  are they dead in the water.
- Will the test repeatedly penalize or reward the same concept over
  and over again on the test.
- Do I cover all the concepts I want to assess.
- Do you make kids waste time with boilerplate code. 
- Do the questions take so long to read and digest that there's little
  time to form and write down answers.
- Do the answers convey anything about the students thought process or
  just correctness.
- Is it easy or impossible to grade and grade fairly. 

What about length? To me a well crafted test should be completed by
the average student with a few minutes to spare - enough time to check
a couple of answers. This is not to say that they'll ace the exam,
just finish it. Far too many teachers make tests an assessment of
speed and accuracy at speed rather than understanding. That might
actually be important in certain contexts - preparing for the APCS-A
multiple choice section as an example but in general, it's not a good
way of assessing what a student really knows. 

It's also important that the the average student can achieve a score
that you expect from an average student. That's probably in the 80s on
a 0-100 scale or a B. Yes, I know, C is supposed to be average but
with grade inflation being what it is...

You should *NOT* give an assessment where the average score is
something like 17 out of 100 with the top student earning a 37. Sure,
you can curve it but it also places a lot of stress on the
students. You might do this from time to time - you might misjudge the
difficulty of a test or your class but it shouldn't be a regular
occurence. Teachers sometimes forget about the psychological affect
that a unfair test can have on a student even if the teacher "fixes" it
after the fact.

** Don't be afraid to experiment or have some fun.

It's also ok to try different things. One year, having just completed
a unit on Cellualar Automata I decided to give a quiz. I figured it
would take the kids 10 to 15 minutes so I gave them 30. The quiz was
something like the following:

#+BEGIN_QUOTE
You have 30 minutes to compose something on a sheet of paper that when
I review it convinces me that you know something about the Cellular
Automata Unit we just completed.
#+END_QUOTE

Some kids loved the quiz, some hated it. The ones that hated it had
been trained for years as expert standardized test takers and this
level of freedom really freaked the out.

Another time, I gave a multi page test of serious questions mixed with
crazy shenanigans. Question one would be some CS problem followed by
some instructions like "stand up, do 5 jumping jacks and sit down" or
"shout out your favorite olde timey exclamation" or even "stand up, if
or when you see another student standing, switch seats with the and
continue the test." The test started with explicit instructions not to
read ahead but to read and do each question in order. The last page
was the answer key and I asked the kids to self-grade. Interestingly
enough the grading was pretty honest. After that one, I received a few
apology emails from kids who read to the end first encouraging me to
give them failing grades for cheating. Wow, I wasn't expecting
that. The test was something of an end of year goof. The CS questions
were really easy - I wanted to reward them with something silly and
easy - a guaranteed A after a year of hard work.

** Tests to drive instruction and future practice

As a final point to ponder, tests shouldn't only be about grades. A
well crafted test should drive instruction. Kids will get answers
wrong - will your questions be crafted so that you can gain insights
into why the got them wrong.

In an early class you might notice things like:

- kids printing rather than returning answers
- kids not understanding scope
- kids having difficulty with idioms like ~i=i+1~
- kids needing more scaffolding to approach a problem

This can drive instruction moving forward.

Over time you'll also learn how to fine tune your tests and other
assessments.

** Next time, we'll talk about projects

Unless of course I get distracted by another blog topic or shiny
object.



