#+BEGIN_COMMENT
.. title: Using Emacs 39 - mu4e
.. slug: using-emacs-39-mu4e
.. date: 2017-12-24 09:00:00 UTC-04:00
.. tags: emacs, learning, tools
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 
I generally use three email accounts. My personal one, work one, and
one for my non-profit. For a couple of years, I've been using mu4e
under Emacs for both my work and non-profit email accounts and gmail
for my personal account. 

I've had lots of requests for a video on what I do but I've been
hesitant for two reasons:
1. There are parts of my configuration that are copied from others and
   I really don't understand.
2. I wasn't happy with the complexity and some of the tooling.

While there are still parts of my configuration that I'm not 100%
clear on I've cleaned up the tooling and complexity by using mu4e only
for my work email for the time being and by switching to mbsync. 

Here's a writeup on configuring things with video at the end.

Unless you run an email server on your local machine using mu4e can be
thought of as three parts.

1. Get the email from the server to the local machine using IMAP.
2. Setting up mu.
3. Access the email locally from Emacs.

** Part 1 Getting the email to your local machine using mbsync

I found his terrific blog post by [[https://twitter.com/robstewartUK][Rob Stewart]] on setting up [[http://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html][mbsync and
mu4e]]. Read it over. I basically followed his directions for setting up
[[https://sourceforge.net/p/isync/isync/ci/master/tree/][mbsync]]. To build from source under Linux, I used the sequence:
#+BEGIN_SRC bash
./autogen.sh
./configure
make
sudo make install
#+END_SRC

I followed Rob's instructions basically verbatim for the password and
authentication stuff so I suggest you do the same. 

You'll also have to make sure to make the necessary email directories
manually. I describe all of this in the video.

** Part 2 - setting up mu.

To set up mu, clone it from git://github.com/djcb/mu.git and build
it. You can find dependencies [[https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html][here]] and then follow the same sequence
used to build mbsync listed above.


Since I store my local email under a folder ~Maildir~  which is what
mu defaults to I can start using it by indexing my emails:

#+BEGIN_SRC bash
mu index
#+END_SRC

The video shows some examples of using mu from the command line and
you can look at the mu cheatsheet [[http://www.djcbsoftware.nl/code/mu/cheatsheet.html][here]]. 


** Setting up mu4e in emacs

Finally, you can set up mu4e in emacs. Take a look at Rob's
configuration in his post or my [[https://github.com/zamansky/using-emacs/blob/master/mu4econfig-sample.el][sample]] config. You'll have to take a
few minutes to go through either and make the appropriate changes but 
the required changes should be cleared.

The video goes through all of this and then a brief demo of how I use
mu4e.

I'm very happy with it and plan to integrate my non-profit email and
maybe even personal email into it soon.

Enjoy:


#+BEGIN_EXPORT HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/newRHXKm4H4" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
#+END_EXPORT








