#+BEGIN_COMMENT
.. title: Getting Ready To Go Back
.. slug: getting-ready-to-go-back-2018
.. date: 2018-08-03 14:23:32 UTC-04:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 
It's August 3rd and I've been giving a lot of thought to the start of
the semester. Normally I wouldn't think about the Fall term this
early. While I've been working on and off since last semester ended, I
don't officially "go back" until August 23rd with classes starting on
the 27th. The difference is that for the first time in forever we're
taking a longish trip between now and then.

We're heading over to Harrogate England. We've never been but Natan's
taking part in the [[http://www.gsfestivals.org/][International Gilbert and Sullivan Festival]] so we
figured we'd follow and play tourist while he was rehearsing and
otherwise doing the festival. I'm looking forward to the trip but
don't expect to get much prep work done while we're there.

So, what's coming this semester?

* Classes

Hunter's honors program has grown big time so I'll be teaching two
classes instead of one this semester. One section will be our
pre-major CS course and one will be our CS1. I've done both before so
I won't need a lot of advance prep. Besides, I learned long ago that
no matter how much prep you do, everything changes once you get in the
classroom with a new batch of kids. Better just to have starter
material and a direction since everything's going to change after day
one anyway.

* Teacher Ed stuff

On the teacher education program front, we've got to send a few items
back through governance for approval. Instead of having teachers in my
programs take a separate fieldwork course, I integrated it into my
curriculum development course. Another change that we have to make,
believe it or not, is to remove the words "for teachers" and "for
educators" from two of the pure computer science courses in the
program. Fortunately, I've done all the prep work needed to get these
going come late August. We're still planning on starting our first
cohort in the Spring.

* Other stuff

Here's where a lot of the fun stuff is happening. Like last year, I'm
planning on doing a lot of outreach to high schools to talk about
colleges, tech, and Hunter. The outreach's [[https://cestlaz.github.io/posts/hunter-cs-year-two/][really made a difference]]
but it take a lot of time since it's all about school visits. I'm
hoping to get to some parents association meetings as well this year. 

I'm also planning a number of new things for our Hunter CS students
and I'd love to jump on the planning now but these things really have
to wait until the term starts. Here's some of what's on tap:

- A monthly CTLE session for CS teachers.
- A monthly tech talk / meetup at Hunter for CS students.
- Finding more and more internship opportunities for the kids. 
- A series of open source workshops I'm coordinating with MongoDB.
- I'm hoping to work out some workshops for the kids with [[https://www.redballoonsecurity.com/][Red Balloon
  Security]]
- And a new tech mentoring program I'm hoping to get off the ground.


I'm sure some of these plans will change. I think I'm pretty ready to
go for the fall but I'll still mull things over for the next few
weeks. 



